### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by mmmmaaaaarrrrrrkkkkkkkk** [LordsTrident/trident-editor#1]
removed

**Comment by LordOfTrident** [comment]
what is your issue

**Comment by pressenterdev** [comment]
tr-ed

**Comment by pressenterdev** [comment]
lol

**Comment by pressenterdev** [comment]
hahahahah

**Comment by MusicOnStereo** [comment]
> tr-ed hahahahaahhaahahahahahahahahahahahahahahahahaahaha
> 
> ### >:)

Use github for what it's supposed to be used for. please.

**Comment by pressenterdev** [comment]
trolled

**Comment by MusicOnStereo** [comment]
scratch github vibes

**Comment by pressenterdev** [comment]
> > tr-ed hahahahaahhaahahahahahahahahahahahahahahahahaahaha
> > ### >:)
> 
> Use github for what it's supposed to be used for. please.

no hahahaha you have no power over tr-ed

**Comment by pressenterdev** [comment]
> scratch github vibes

OMG SWEAR YOU CANT SAY SCR*TCH

**Comment by MusicOnStereo** [comment]
bruh

**Comment by pressenterdev** [comment]
ok this was a joke bye

**Comment by pressenterdev** [comment]
![giphy](https://user-images.githubusercontent.com/94125865/145694280-8af0e25e-d152-4dec-a852-00fe68397d39.gif)

**Comment by MusicOnStereo** [comment]
stop

**Comment by MESYETI** [comment]
shut up

**Comment by CubeyTheCube** [comment]
unbased

**Comment by MESYETI** [comment]
hello

**Comment by MESYETI** [comment]
hi github channel

**Comment by MESYETI** [comment]
no
